version: '3.9'

services:
  mic-publicback:
    build: 
        context: mic-publicback 
        dockerfile: Dockerfile
    image: mic-publicback:latest      
    ports:
        - "8081:8080"
    restart: always
    environment:  
        - "baseurl.emailsender=http://mic-emailsender:8080"
        - "baseurl.subscription=http://mic-subscription:8080"
  mic-subscription:
    build: 
        context: mic-subscription 
        dockerfile: Dockerfile
    image: mic-subscription:latest
    ports:
        - "8082:8080"
    restart: always
    links:
        - mongodb
    depends_on:
        - mongodb
    environment: 
      - spring.data.mongodb.authentication-database=adidas-subscriptions
      - spring.data.mongodb.database=adidas-subscriptions
      - spring.data.mongodb.host=mongodb
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.username=username
      - spring.data.mongodb.password=usernamep
  mic-emailsender:
    build: 
        context: mic-emailsender 
        dockerfile: Dockerfile
    image: mic-emailsender:latest
    ports:
        - "8083:8080"
    restart: always  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ~/apps/mongo/data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=usernamep
      - MONGO_INITDB_DATABASE=adidas-subscriptions
    